### ISSUE TITLE
Which license this project has?

### ISSUE THREAD

**Issue by Wohlstand** [caseif/wednesday.exe#5]
I did a brief look on this code, and I found there is no license defined. So, which license this project has?

**Comment by caseif** [comment]
Sorry, it looks like this was an oversight on my part when creating the repository. My intention was to release the project under an open-source license; however, I don't believe I presently have the right to add one now due the presence of contributions from @Ungaminga. I can send them an email asking permission to relicense, although they don't seem to currently maintain an online presence under that alias so I'm not sure whether I'll hear back.

In any event, you (and anyone else) hereby have license to use my contributions to this project under the MIT License. I'll add a license file shortly outlining this.

**Comment by Wohlstand** [comment]
~~If you speak about resources, feel free to keep the original author's license or just keep a notice that these files are owned by @Ungaminga. For your source codes, you can give your own license easily. There is a doze of projects that has different licenses between the source code of the engine and the license for resources (pictures, sounds, music, videos, etc.)~~
Sorry, had to read it un-carefully, you meant part of the source contributed, ye. Anyway, I'll take a look at the legal possibility about contributions.

**Comment by caseif** [comment]
Thanks for pointing out the copyright of the resources, that had slipped my mind but I'll be sure to include a blurb in the LICENSE file.

IANAL but you may be able to get away with using HEAD if you revert cf0091b9703938c9fef55ab9cdddacd95590cc0b - there are a couple of other commits by the contributor but because they're effectively just tweaks to constant params, I'm not sure whether they would rise to the standard of being copyrightable (but again, IANAL and this is not legal advice).

**Comment by caseif** [comment]
LICENSE file has been added, thanks for bringing this to my attention!

Closing the issue for now, but let me know if you have any other questions re: licensing.
